name: applichiamoci
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'



# ----------------PACKAGES---------------- #

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.2
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  lottie: ^2.7.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  maps_launcher: ^2.2.0


  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0

  # Firebase
  firebase_storage: ^11.5.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true



  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/content/user.png
    - assets/images/home/
    - assets/images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
