// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANavH03YsZ_CTKAWnyoUCblYV6DfeTnnI',
    appId: '1:536809525168:web:03959d092cc6e62c149075',
    messagingSenderId: '536809525168',
    projectId: 'applichiamoci-fondazione',
    authDomain: 'applichiamoci-fondazione.firebaseapp.com',
    storageBucket: 'applichiamoci-fondazione.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYbWq8W9hDh9C8p9e1WMqiWUz0dA36uY',
    appId: '1:536809525168:android:4536e648bef2c92c149075',
    messagingSenderId: '536809525168',
    projectId: 'applichiamoci-fondazione',
    storageBucket: 'applichiamoci-fondazione.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYwNGzkYrSOOKWB76yhEfI_--ee-ZMmPc',
    appId: '1:536809525168:ios:71d1ee1badde2ef3149075',
    messagingSenderId: '536809525168',
    projectId: 'applichiamoci-fondazione',
    storageBucket: 'applichiamoci-fondazione.appspot.com',
    androidClientId: '536809525168-q5a2r8a808nsjhf2dradriejvv1is86q.apps.googleusercontent.com',
    iosClientId: '536809525168-oc0t70i28nisdo4jnh3br3tjpacs2og1.apps.googleusercontent.com',
    iosBundleId: 'com.example.applichiamoci',
  );
}
